trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run lint
    npm test
  displayName: 'Install dependencies, Lint, and Test'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifactName: 'Demo_WebApp_Build'
    publishLocation: 'pipeline'
